# Generated by Django 4.2.8 on 2023-12-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_menu_id_questionanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='optoiona',
            new_name='optionA',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='optoionb',
            new_name='optionB',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='optoionc',
            new_name='optionC',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='optoiond',
            new_name='optionD',
        ),
    ]
