# Generated by Django 4.2.8 on 2023-12-28 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_optoiona_questionanswer_optiona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa', to='api.menu'),
        ),
    ]
